### PR TITLE
added Subtitle property to tracks

### PR DESCRIPTION
**Pull request by ghost**
added some missing xml comments
VS forced me to reinstall the corresponding libraries
added Subtitle property to tracks to see remixes etc.

### CODE REVIEW

**Comment by robertmclaws** [comment]
Was there an error when re-checking for the tokens? because my not awaiting the Authenticate call on Line 321 was intentional, it will happen behind the scenes so there is no reason to block the thread...

**Comment by MSiccDev** [comment]
VS gave me the hint that the call needs to be awaited. Seems I misread your comments. Will update it once again if needed to merge my request.

**Comment by MSiccDev** [comment]
removed await and commited again.

**Comment by robertmclaws** [comment]
Unfortunately, I'm not going to be able to accept this pull request, due to the configuration changes it made to the project. But I have updated the documentation, as well as added several new fields from their latest release. Sometime this week I will also add their new APIs for getting playlists and streaming music.

If you find any other improvements that need to be made, please let me know. Thanks!

**Pull request closed without merging**
